// Package sanitizer is the buyer-side privacy proxy described in
// docs/cli/channel-marketplace.md §7-2.
//
// Lifecycle:
//
//	everyapi proxy start  →  listen on :8888
//	buyer SDK ──────────▶  proxy intercepts
//	                       1. detect sensitive substrings in the request body
//	                       2. replace each with a stable placeholder
//	                       3. forward to https://api.everyapi.ai
//	                       4. on response (streaming or buffered), undo the
//	                          substitution before returning bytes to the SDK
//
// The mapping table lives only in this process's memory and is dropped
// at shutdown. The platform never sees the real values, only the
// placeholder strings; the platform also cannot inject a placeholder
// the proxy doesn't recognise (the mapping is local-only), so a
// malicious upstream response can't trick the proxy into emitting
// attacker-controlled text into the SDK.
package sanitizer

import (
	"fmt"
	"regexp"
)

// PlaceholderPrefix / PlaceholderSuffix wrap the per-secret id. The
// bracketing chosen here is deliberately unusual so it never collides
// with anything an LLM is likely to emit on its own:
//
//   - `<<__` and `__>>` aren't valid HTML / Markdown / JSON syntax in
//     the same byte sequence
//   - all-caps "EVERYAPI_SECRET" makes it visually obvious in a prompt
//     dump that the value got substituted
//
// The format MUST be stable across processes — when prompt caching is
// in play on the upstream, identical secret values must map to the
// SAME placeholder string so the cache key doesn't rotate (spec §7-2:
// "Stable mapping: 同一真实值 → 同一 placeholder string … 保证 prompt
// caching 仍命中"). The per-secret id is monotonic within a process
// (see mapping.go), so the placeholder stays stable inside a session.
const (
	PlaceholderPrefix = "<<__EVERYAPI_SECRET_"
	PlaceholderSuffix = "__>>"
)

// MakePlaceholder returns the wire form for the given numeric id. Ids
// are zero-padded to three digits because 99% of real prompts have
// <100 secrets and the fixed width keeps the placeholder visually
// uniform — but a 4+ digit id still works, the rendered string just
// gets wider.
func MakePlaceholder(id int) string {
	if id < 1000 {
		return fmt.Sprintf("%s%03d%s", PlaceholderPrefix, id, PlaceholderSuffix)
	}
	return fmt.Sprintf("%s%d%s", PlaceholderPrefix, id, PlaceholderSuffix)
}

// placeholderRE matches a fully-formed placeholder. Used by the
// streaming downstream pass to find substitution targets in upstream
// responses. ASCII-only on purpose — the placeholder body is
// generated by us, so anchoring to digits is safe.
var placeholderRE = regexp.MustCompile(regexp.QuoteMeta(PlaceholderPrefix) + `\d+` + regexp.QuoteMeta(PlaceholderSuffix))

// FindPlaceholders returns the byte spans of every complete
// placeholder inside s.
func FindPlaceholders(s string) [][]int {
	return placeholderRE.FindAllStringIndex(s, -1)
}

// PartialAtTail reports whether the suffix of s might be the prefix
// of a placeholder that hasn't streamed in yet. The longest possible
// partial match is `len(PlaceholderPrefix) - 1` bytes (`<<__EVERYAPI_SECRET_`
// minus the closing char). Plus all the digits up until — but not
// including — `__>>` could be present.
//
// Used by the streaming response transformer to decide how many bytes
// at the end of a chunk to hold back as "carryover" pending the next
// chunk. We can't blindly carry over the maximum-placeholder-length
// bytes because we'd starve callers expecting promptly-flushed
// streams; we can't always emit the whole chunk because half of a
// placeholder split across two chunks would never get reassembled.
//
// Returns the byte offset where the partial match starts, or -1 if no
// suffix of s could grow into a placeholder.
func PartialAtTail(s string) int {
	if len(s) == 0 {
		return -1
	}
	// First check: any byte in the last (len(prefix)-1) bytes could
	// be the start of a fresh prefix.
	maxTail := len(PlaceholderPrefix) - 1
	if maxTail > len(s) {
		maxTail = len(s)
	}
	for i := len(s) - maxTail; i < len(s); i++ {
		if i < 0 {
			continue
		}
		rem := s[i:]
		// Check if rem is a proper prefix of PlaceholderPrefix
		if len(rem) <= len(PlaceholderPrefix) && PlaceholderPrefix[:len(rem)] == rem {
			return i
		}
	}
	// Second check: we may already be inside the body — the prefix
	// is complete but `__>>` hasn't streamed yet. Scan from the end
	// backwards for the most recent prefix occurrence; if it has no
	// closing suffix after it, hold back from that index.
	last := -1
	for i := 0; i <= len(s)-len(PlaceholderPrefix); i++ {
		if s[i:i+len(PlaceholderPrefix)] == PlaceholderPrefix {
			last = i
		}
	}
	if last >= 0 {
		tail := s[last:]
		// Are there any non-digit, non-PlaceholderSuffix-prefix
		// bytes after the prefix? If so, this isn't a partial
		// placeholder — it's just literal text that starts with our
		// prefix. We hold back anyway (false positives are cheap;
		// the next chunk decides).
		body := tail[len(PlaceholderPrefix):]
		for j := 0; j < len(body); j++ {
			c := body[j]
			if c >= '0' && c <= '9' {
				continue
			}
			// Past the digits — must be the start of `__>>`. If the
			// next bytes match a prefix of PlaceholderSuffix, hold
			// back; otherwise it's just literal text and we don't
			// need to carry over.
			rem := body[j:]
			if len(rem) >= len(PlaceholderSuffix) {
				// Full suffix present — already a complete
				// placeholder; placeholderRE will catch it on the
				// emit pass, no carryover needed for this match.
				if rem[:len(PlaceholderSuffix)] == PlaceholderSuffix {
					return -1
				}
				// Past the digits, suffix isn't valid — literal
				// text starting with our prefix. No carry.
				return -1
			}
			// Partial suffix present
			if PlaceholderSuffix[:len(rem)] == rem {
				return last
			}
			// Some other character — not a placeholder.
			return -1
		}
		// All digits, no suffix yet — hold back.
		return last
	}
	return -1
}
